import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className='flex items-center justify-between'>
        <Link href='/'>
          <a>
            <Image
              src='/icon-adidas-logo.svg'
              alt='logo'
              width='40px'
              height='40px'
            />
          </a>
        </Link>

        <section className='flex justify-between'>
          <Link href='/'>
            <a>Men</a>
          </Link>
          <Link href='/'>
            <a>Women</a>
          </Link>
          <Link href='/'>
            <a>Kids</a>
          </Link>
          <Link href='/'>
            <a>Sale</a>
          </Link>
          <Link href='/'>
            <a>3 Stripe Life</a>
          </Link>
        </section>
        <section>
          <input type='search' name='' id='' />
          <button>Profile</button>
          <button>Checkout</button>
        </section>
      </header>
      <main>
        <h1 className='text-3xl font-bold underline'>
          Welcome to Loky Webshop!
        </h1>
      </main>
    </div>
  );
};

export default Home;
