import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/layout';
import Image from 'next/image';
import Button from '../components/Button';
import { useEffect, useState } from 'react';
import { createClient } from 'contentful';

const Home: NextPage = () => {
  const [products, setProducts] = useState<any[]>();

  const client = createClient({
    space: process.env.NEXT_PUBLIC_SPACE!,
    accessToken: process.env.NEXT_PUBLIC_ACCESS_TOKEN!,
  });

  useEffect(() => {
    client.getEntries().then((res) => {
      console.log(res.items);
      setProducts(res.items);
      console.log(products);
    });
  }, []);

  return (
    <div className='flex flex-col items-center'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <section
          className="h-[600px] flex flex-col w-full bg-cover p-16
        bg-[url('/running-ss22-ultraboost-educate-catlp-masthead-large-2-d_tcm221-860848.webp')]"
        >
          <h2 className='font-extrabold text-4xl mt-16 w-3/12'>
            RUN WITH ULTRABOOST 22
          </h2>
          <p className='font-light my-3 w-4/12'>
            Supreme energy return meets 360° fit improvement. Own your energy
            and achieve your impossible in the Ultraboost 22 running shoe.
          </p>
          <Button text='Shop women' />
          <Button text='Shop men' />
          <Button text='Shop kids' />
        </section>
        <section className=' flex justify-between '>
          {products &&
            products.map((el) => {
              return <p key={el.fields.id}>{el.fields.title}</p>;
            })}
        </section>
      </Layout>
    </div>
  );
};

export default Home;
